import Foundation
import KanpanCore

/// Trader-facing evidence wording shared by native insights views. Keep thresholds explicit and claims observational.
public enum OrderFlowInsightLabels {
  public static let title = "盘口洞察"
  public static let current = "当前观察"
  public static let beijingTime = "北京时间"
  public static let currentBar = "当前这根"
  public static let selectedBar = "选中这根"
  public static let keyLevels = "附近关键挂单"
  public static let primaryOnly = "主图品种"
  public static let above = "上方卖盘"
  public static let below = "下方买盘"
  public static let noWall = "暂无可确认的挂单区"
  public static let remaining = "剩余"
  public static let matched = "已匹配成交"
  public static let duration = "持续"
  public static let todayZones = "今日大单聚集区"
  public static let today = "今日"
  public static let actualPrices = "真实成交价 · 分源"
  public static let threshold = "门槛"
  public static let loading = "正在整理成交信息"
  public static let unavailable = "暂无真实价区数据"
  public static let untracked = "这只品种暂未持续记录"
  public static let timeRule = "本页时间均为北京时间；今日从北京时间零点计算。"
  public static let insufficient = "覆盖不足，继续观察"
  public static let noExecutions = "已覆盖时段暂无大额成交"
  public static let recent = "近15分钟"
  public static let buy = "主动买"
  public static let sell = "主动卖"
  public static let flowReaction = "大额成交与价格反应"
  public static let endedMinutes = "已结束分钟"
  public static let noPrimaryFlow = "暂无主图品种的大额成交数据"
  public static let priceMissing = "同所连续分钟价格不足"
  public static let liquidation = "爆仓与后续反应"
  public static let aggregate = "跨所合约 · 分钟统计"
  public static let longLiquidated = "多头被平"
  public static let shortLiquidated = "空头被平"
  public static let noLiquidation = "该时段未观测到爆仓"
  public static let noLiquidationData = "暂无爆仓数据"
  public static let liquidationSampling = "已接入交易所的强平推送存在采样；与大单成交可能重叠，不相加。"
  public static let changes = "最近重要变化"
  public static let lastHour = "近15分钟 · 分源"
  public static let noChanges = "暂未记录重要挂单变化"
  public static let lost = "失联结束 · 后续未知"
  public static let live = "新增有效挂单"
  public static let filled = "已成交消耗"
  public static let cancelled = "挂单已减少退出"
  public static let evidence = "判断依据"
  public static let candidate = "观察状态，不预测方向"
  public static let evidenceRule = "主动单边占比达到60%才描述偏向；价格变化以0.05%区分推进。价格取主图交易所相同窗口的连续1分钟K线。"
  public static let zoneRule = "价区来自实际大额成交，按成交额排序。成交密集本身不等于支撑或压力；不同交易所的价区分别保留。"
  public static let wallRule = "仅将主图交易所、产品和合约完全匹配的挂单作为附近流动性。成交消耗只认同一本簿的成交匹配。"
  public static let entryHint = "上滑查看关键价位与成交反应"
  public static let returnCurrent = "关注当前"
  public static let locate = "回图定位"
  public static let partial = "部分覆盖"
  public static let noPriceAfter = "爆仓后完整分钟不足，等待观察"
  public static let minutePrice = "同所价格"
  public static let evidenceEmpty = "证据不足，暂不作判断"
  public static let from = "从"
  public static let since = "起"
  public static let held = "数据更新停在"
  public static let minimumTrade = "成交门槛"
  public static let total = "大额成交"
  public static let observedSpot = "已观测现货"
  public static let observedContract = "已观测合约"
  public static let observedSources = "已观测来源 · 跨所聚合"
  public static let aggregateTrades = "跨所成交"
  public static let initialSize = "初始规模"
  public static let buyShare = "主动买占比"
  public static let thresholdNote = "成交统计采用服务端统一门槛，挂单门槛在右上角调整。"
  public static let noLiquidationAfter = "该时段未观测到爆仓，暂无后续观察"

  public static func minutes(_ n: Int) -> String { "近\(n)分钟" }
  public static func observation(_ o: OrderFlowInsightDigest.Observation) -> String {
    switch o {
    case .buyAdvance: "主动买入偏多，伴随价格上移"
    case .sellAdvance: "主动卖出偏多，伴随价格下移"
    case .buyNoAdvance: "主动买入偏多，价格暂未推进"
    case .sellNoAdvance: "主动卖出偏多，价格暂未推进"
    case .buyAgainst: "主动买入偏多，价格仍下移"
    case .sellAgainst: "主动卖出偏多，价格仍上移"
    case .balanced: "主动买卖暂未形成明显偏向"
    case .insufficient: evidenceEmpty
    }
  }
  public static func afterLiquidation(_ percent: Double, long: Bool) -> String {
    if abs(percent) < OrderFlowInsightDigest.priceMovePercent { return "该分钟爆仓后，价格暂未继续推进" }
    if long { return percent > 0 ? "该分钟多头爆仓后，价格出现回升" : "该分钟多头爆仓后，价格继续下移" }
    return percent < 0 ? "该分钟空头爆仓后，价格出现回落" : "该分钟空头爆仓后，价格继续上移"
  }
}
